### ISSUE TITLE
Add/Change documentation of ISO images for VM installations

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#1036]
If ISO images are added to the download page (https://dietpi.com/#downloadinfo), the usage of the ISO images need to be added/changed in the installation description e.g. there: https://dietpi.com/docs/install/#how-to-install-dietpi-proxmox.

See also https://github.com/MichaIng/DietPi-Website/pull/344

**Comment by MichaIng** [comment]
The idea was to have the detailed manual VM creation steps in an expandable info box, and promote https://github.com/dazeb/proxmox-dietpi-installer instead as default option for the QCOW2 disk images, the installer ISOs as new alternative options. So our instructions are shorter and easier by default.
