### ISSUE TITLE
Do spell check before link check

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#141]
Is it possible to execute the spell check before the link check runs?  
Due to the long runtime of the link check I would be able to correct markdown issues as well as spell check issues during the time consuming run of the link check.

**Comment by MichaIng** [comment]
Good idea, will switch it.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi-Docs/commit/e3197559bbdd69df154377c36b29ba33a7d0a3af
