### ISSUE TITLE
Porting Remote Desktop Access

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#144]
File remote_desktop.md.

**Comment by MichaIng** [comment]
Hmm, automatic closure via merging PR somehow does not work. I recognised this on DietPi main repo as well, sometimes it works, sometimes not. Probably the approvals are required first, not sure.

**Comment by StephanStS** [comment]
Not a big issue.

The status signalling with [DRAFT] like Petru did in combination with the 'Draft' property and linking to the issue is fine for me. 
After the PR has finished (and the checks have run!) we can finish the rest on the board and in the issue list by hand.
