### ISSUE TITLE
Software overview on dietpi.com: Add a link to the "new" doc pages from the tiles

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#228]
There: <https://dietpi.com/dietpi-software.html>

Idea: Add a link to the "new" documentation software pages from the tiles.  
Rename the basic text for this linking to "Once installed" -> "Further information".

Start with one tile and then review for further decision.

- [x] **Next step:** Continue to work and discuss on this topic

**Comment by MichaIng** [comment]
This is done, right?
