### ISSUE TITLE
Description of Webserver stacks: Exchange the three bullets with the description "behind the links"

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#231]
Section [Webservers](https://dietpi.com/docs/dietpi-software-webserver-stack/#webservers): Exchange the three bullets with the description "behind the links" ([*Webserver Preference System*](https://dietpi.com/phpbb/viewtopic.php?p=1549#p1549)):
   - Remove the links, but keep the three bullets
   - Port the description *Webserver Preference System* to this section

**Comment by fpetru** [comment]
Extended the spec and made the connection with the **Webserver Preference** configuration option, with the detailed description of the webservers & web stacks. 

https://github.com/MichaIng/DietPi-Docs/pull/294
