### ISSUE TITLE
Describe Databases in "Optimized Software", "Web Development"

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#237]
Redis actually only in `dietpi-software` present.

**Comment by MichaIng** [comment]
I changed it for a general database description. I can do it for MariaDB and SQLite. I think Petru knows more about InfluxDB and Redis, when it's about technical wording (I just know how to use it with Nextcloud and other applications which provide a config mask, and that it is purely non-persistent RAM-based database).
