### ISSUE TITLE
Python: Add further descriptions

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#250]
See <http://localhost:8000/software/programming/#python-high-level-interpreted-programming-language>.  
The Python description needs to be extended (e.g. logging, installation directory,...).

The original chapter part to be generated was called:  
*Python 3 & Flask - Micro web framework powered by Python*

**Comment by MichaIng** [comment]
There is no special install directory or logging, it is distributed across the regular FHS directory structure. Instead, we should add some note that especially the `pip`/`pip3` Python package manager and development headers are included, and how to use it (`pip3 install -U <module>`). Also, the install option explicitly only installs Python 3, which should be made clear as well.

**Comment by StephanStS** [comment]
Ok, taken over your input.
