### ISSUE TITLE
Add docs for VMware ESXi support on DietPi (installation notes) 

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Docs#258]

**Comment by StephanStS** [comment]
I will start with a description how to use DietPi within the VMware Player.

**Comment by StephanStS** [comment]
Basic VMware installation was described with PR #346. 
The ESXi support needs to be described (in an own tab).

**Comment by StephanStS** [comment]
ESXI installation was linked to <https://ccie.tv/running-dietpi-vmware-image-on-esxi-6-7/> in the VMware installation description ("Install in VMware Player" tab): 

> For information about running DietPi in an VMware ESXi environment, you can read this article: [Running the DietPi VMware image on ESXi 6.7](https://ccie.tv/running-dietpi-vmware-image-on-esxi-6-7/).

This should be enough to close this issue.
