### ISSUE TITLE
Documentation on Advanced configuration options

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Docs#259]
Detail dietpi.txt options. There are multiple options, including the option to automatically install a set of software titles on first boot.

**Comment by fpetru** [comment]
@MichaIng - As I remember we have a detailed spec on the available configuration options in Github. Could you please share the link, and I will be able to start porting also to Docs portal.

**Comment by MichaIng** [comment]
I'm afraid there is no detailed information about this, aside of what can be found in the [dietpi.txt](https://github.com/MichaIng/DietPi/blob/master/dietpi.txt) file itself.
Automated first run installs is documented here as well: https://dietpi.com/phpbb/viewtopic.php?t=273

While I agree that we should add a detailed documentation section about this, as well the file itself should be self-explaining, IMO.

One thing that could or should be pointed out somewhere, as well in the text file itself, is which options really only have an effect on first boot, which have an effect directly when changing in the text file only, and which ones are more flags for our scripts to identify or store choices made within the GUI tools, but have no or even bad effect when changing manually only in the text file. E.g. enabling IPv6 requires to change the sysctl config, so editing only the text file makes other scripts believe that IPv6 is enabled while it may be not, which could lead to failing service starts (e.g. when attempting to bind to IPv6 IPs). But this setting has an effect on first boot, where it is parsed and IPv6 enabled or disabled accordingly. Similar with `CONFIG_SERIAL_CONSOLE_ENABLE`.

**Comment by StephanStS** [comment]
Some features of the configuration are also described there: <https://dietpi.com/phpbb/viewtopic.php?p=1140#p1140>.

**Comment by fpetru** [comment]
Shall we create a page in Docs, where we have these 3 scenarios:
  
- Example: Configure and run a completely automated installation
- Example: Pre-configure for WiFi
- Example: Enable automated APT package update (_this configuration is included in the release notes - it's easy to miss it_)

**Comment by StephanStS** [comment]
If we do this description we also should not forget to redirect the link <https://dietpi.com/phpbb/viewtopic.php?p=1140#p1140> which is located under the ["DietPi - features overview"](https://dietpi.com/#features) "DietPi Automation" icon to the new description.

**Comment by StephanStS** [comment]
An idea to handle this issue:

At least the user has to know that he can edit dietpi.txt, this should be mentioned within https://dietpi.com/docs/install as an own section.
Also the typical basic settings could be explained, e.g.
AUTO_SETUP_LOCALE,
AUTO_SETUP_KEYBOARD_LAYOUT,
AUTO_SETUP_TIMEZONE,
WiFi, WiFi-Country,
AUTO_SETUP_NET_HOSTNAME,
AUTO_SETUP_AUTOMATED,
AUTO_SETUP_GLOBAL_PASSWORD,
SURVEY_OPTED_IN,
CONFIG_CHECK_DIETPI_UPDATES,
CONFIG_CHECK_APT_UPDATES,
AUTO_SETUP_INSTALL_SOFTWARE_ID

**Comment by MichaIng** [comment]
Network, localisation, and all directly related to unintended first run setup, I'd say are most important, hence, additionally to your list AUTO_SETUP_ACCEPT_LICENSE. As long as the DietPi/APT update check options are not implemented into the dietpi-update GUI, it make sense to give them some priority here as well.

**Comment by StephanStS** [comment]
Also on https://dietpi.com/#features the icon "DietPi-Automation" needs to be redirected to the new description.

**Comment by StephanStS** [comment]
Add link to https://blog.login.gmbh/vollautomatische-installation-eines-raspberry-pi-unter-dietpi-schritt-fuer-schritt/ where Holger describes this.

**Comment by StephanStS** [comment]
See also on the Friendlyarm wiki page: https://wiki.friendlyarm.com/wiki/index.php/DietPi#Configure_dietpi.txt

**Comment by StephanStS** [comment]
Also this option is new: See [Allow to turn first DHCP assigned IP into static IP](https://github.com/MichaIng/DietPi/issues/1674).
