### ISSUE TITLE
Add Portainer software docs

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi-Docs#270]
PR: https://github.com/MichaIng/DietPi/pull/3933

Need to add Portainer docs before 6.34 release 😉
- [x] Include screenshot from web UI

**Comment by cocoflan** [comment]
https://codeopolis.com/posts/beginners-guide-to-portainer/

**Comment by Joulinar** [comment]
well usually we don't add fill software docs. More basic thinks like how to access. But we could link this guide or the offical docs

**Comment by cocoflan** [comment]
Ok linking the page as a basic help looks good for me. :-)

**Comment by fpetru** [comment]
@cocoflan @Joulinar - I have added a basic documentation

**Comment by Joulinar** [comment]
ah cool thx @fpetru 
btw is there a URL for testing?

**Comment by fpetru** [comment]
Hi @Joulinar

thanks for your PR review - fixed and made a new PR.
No, there is not yet any test.

**Comment by MichaIng** [comment]
Page can be reviewed now here: https://dietpi.com/test/software/programming/#portainer
