### ISSUE TITLE
Add v6.34 release notes

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#271]
https://github.com/MichaIng/DietPi/pull/3960
- [ ] Add links from the changelog key words to the related doc pages

**Comment by StephanStS** [comment]
I added a couple of links to the file <https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt> via [PR #3962](https://github.com/MichaIng/DietPi/pull/3962).

**Comment by MichaIng** [comment]
And I removed them, since it is a pure text file that needs to be nicely shown in console, e.g. we have a changelog viewer in dietpi-update 😉. I added the links instead here: https://github.com/MichaIng/DietPi/pull/3960

**Comment by fpetru** [comment]
Included links
