### ISSUE TITLE
Time sync on VirtualBox with Guest tools => VBoxService

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#287]
With DietPi guest tools installed, VBoxService runs as time sync daemon to sync time with the host machine. In such case, `systemd-timesyncd` (which is invoked by DietPi's config option) wont start and hence should be disabled:
`dietpi-config` > Advanced Options > Time sync mode > Custom.

**Comment by StephanStS** [comment]
Actually I am investigating VBox with different timed sync options and their behaviour at "VBox machine reboot", "VBox machine sleep mode", "PC sleep mode with running VBox machine".

Basically, if you always shutdown your VBox machine, you do not have any problem.  
Only in sleep mode situations where the PCs clock runs ahead from the VBox machine clock a time sync problem occurs. This problem can lead to `apt update` problems (with outdated files).

Depending on the results I assume that "daemon" will be the best recommendation. Results will be described in the installation chapter.

**Comment by MichaIng** [comment]
So VBoxService is running but not syncing the time with the host when exiting sleep mode? Looks like something we should ask at VBox forum. If I remember right, it should sync every 5 minutes shifting and every 20 minutes a full sync. But I'd expect it to sync directly on boot and as well after exiting any system mode where the system clock (or the service) stops.

**Comment by StephanStS** [comment]
Some results so far:

### A.) Emulated RTC of the VM

Generally, there is a VM emulated RTC (which can be read out via `hwclock`) which runs independent to the Linux system time (which can be read out via `date`).

- These two clocks can be synchronized to each other via 
    - `hwclock --systohc` (the emulated RTC is set to the value of the Linux system time) resp. 
    - `hwclock --hctosys` (the Linux system time is set to the value of the emulated RTC)

### B.) Behaviour in regard of vboxadd-service
1. **Without vboxadd-service** running (i.e. without VirtualBox Extensions installed)
    - Setting in `dietpi-config` to all options except *Custom* works like expected
2. **With vboxadd-service** running
    - Having options except *Custom* leads to an error in `systemctl status systemd-timesyncd`, also at boot time a timeout for the timesync occurs. 
       Stopping then the vboxadd-service (at least removing the symbolic link `/usr/sbin/VBoxService` which links to `/opt/VBoxGuestAdditions-6.1.18/init/vboxadd-service`) helps to run options except *Custom*. 
       (Remark: The symbolic link can also be added manually via `ln -s /opt/VBoxGuestAdditions-6.1.18/init/vboxadd-service /usr/sbin/VBoxService`)
    - t.b.d. ***What happens if option Custom is set?***

### C.) Behaviour at suspend (i.e. no shutdown of the LInux system)
General: The hwclock (as well as the system time) is halted and gets a delay to the host PCs time.

T.b.d.
