### ISSUE TITLE
Add Pi-hole + Unbound documentation

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#288]
Currently both docs are independent and Unbound docs are very minimal and do not really explain the idea behind it and why it is offered together with Pi-hole installs.

A third combined documentation could be added below them to explain, at best via nice picture, how DNS requests are usually done, which actors are involved and who can read them, how things change with Unbound and how with Unbound + DoT (DNS over TLS).

Additionally we need to add a tab to the Unbound documentation about how to enabled DoT, which again requires an upstream DNS provider but sends DNS requests encrypted so that a local ISP cannot read them.

**Comment by StephanStS** [comment]
Possibly the description could also be extended with the squid proxy server (data storage mainly RAM based)?

**Comment by StephanStS** [comment]
See also [Fotooase: Raspberry Pi 4 - Teil 3: Pi-Hole+Unbound Einrichten + Wartung](https://fotooase.com/blog/2020/4/raspberry-pi-4-3).

**Comment by MichaIng** [comment]
Assigning to Petru as well as of the blog post from where we can extract things for a related docs section.

**Comment by StephanStS** [comment]
@fpetru, @MichaIng: I propose to close this issue: The combination is explained in Petrus blog entry and in the dietpi-docs page.

**Comment by MichaIng** [comment]
Agreed, the blog makes a combined documentation probably obsolete. We could still somehow extract the essence for a more compact/technical docs section, but actually the combined install is made so easy with v7.1, that it wouldn't contain much more without doubling the Pi-hole and Unbound sections.
