### ISSUE TITLE
Tab titles do now allow simple Markdown code

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#303]
pymdown extensions have been updated: https://github.com/facelessuser/pymdown-extensions/releases/tag/8.1

> NEW: Tabbed titles can now have simple Markdown in them which can be parsed and rendered (like emoji, bold, etc.).

This means we can do something like:
```
=== "Tab with **fat** word inside 👍"
```

**Comment by fpetru** [comment]
@MichaIng - This is indeed a nice extension !
