### ISSUE TITLE
How to reference official software links/docs?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#305]
We currently show official software links, like website, docs or forum, in various different ways, either inside a content tab, or as simple text below the tabs section, or with a `###` header below the tabs section. Let's agree with and consequently use one way to present those.

#### My suggestion
As such links also serve as kind of credits and backlinks for software developers, actually I like to not hide them behind a tab, but have them always shown. Having a simple text line with the URL is visually probably not enough separated from above tabs content, so it looks like the links may contain further information about the topic of the current tab content, while actually they contain general information, e.g. see Node-RED docs: https://dietpi.com/docs/software/hardware_projects/#node-red
One could misunderstand it a way that https://nodered.org/ contains further information about Node-RED **using port 1880** or such 😉. So I personally prefer a `###` header, like here in case of Bitwarden_RS: https://dietpi.com/docs/software/cloud/#official-links
The only problem with this is that, as can be seen, the element ID (`#official-links`) would not be unique and we would have something like `#official-links-1`, `#official-links-2` etc, as link suffix for those headers, quite ugly. Either we could name the headers like `### Official Bitwarden_RS links`, or with some luck there is a way via Markdown/MkDocs plugins or options to have the `##` header automatically as prefix for `###` header IDs.

However especially when we show more links, a more compact focused impression and less scrolling are arguments to always have links behind a content tab. What do you think?

**Comment by fpetru** [comment]
Very good points ! I have closed my earlier PR until we have a resolution on this. Let's discuss on it soon ;)

**Comment by StephanStS** [comment]
I aggree to add (unique) `###` headings and propose the templates 
- `### Official links <package_name>` 
- `### Credits <package_name>`
and add them if applicapable.

**Comment by MichaIng** [comment]
Credits to Stephan for the idea to simply place a horizontal line before the link list starts:
____
Website: https://dietpi.com
Official documentation: https://dietpi.com/docs/
Source code: https://github.com/MichaIng/DietPi

**Comment by MichaIng** [comment]
-----
_____
