### ISSUE TITLE
Make software FAQ a tab or keep below tabs?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#311]
For PaperMC and DDX-Rebirth we currently have an FAQ section below the links. Shall we make a tab of it or keep it like now? I personally would prefer a tab, since such section could grow and lead to (too?) long scrolling, but this is no strong opinion, so I'd follow yours.

https://dietpi.com/docs/software/gaming/#faq_2

The reason why I come up with this is an FAQ section for Nextcloud.

**Comment by MichaIng** [comment]
Well move it into an own tab.
- [ ] Nextcloud FAQ will be done by @MichaIng

**Comment by MichaIng** [comment]
I started with this for the gaming page. Wanted to add something to PaperMC but could not hold myself to go through the whole page and make various little fixes change changes 😄.

**Comment by StephanStS** [comment]
Already finished it on my PC. Push will follow.

-----Original Message-----

**Comment by MichaIng** [comment]
Ah okay, no problem I'll take care the conflicts to merge them then.

**Comment by StephanStS** [comment]
@MichaIng: Now you could go on. :-)
