### ISSUE TITLE
Add description for Hyper-V virtual machine

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#373]

**Comment by StephanStS** [comment]
@MichaIng, @fpetru: Shall I also structure all Virtual Machines similar to the PC installation?  
See this page: https://dietpi.com/docs/install/. 

---

**Option 1** with all virtual machines flat:
![grafik](https://user-images.githubusercontent.com/57687516/109051289-a6e67000-76da-11eb-9e5b-620b2fc85965.png)

--- 

**Option 2** with sub tabs (all VMs in headline):
![grafik](https://user-images.githubusercontent.com/57687516/109051890-4c014880-76db-11eb-8de3-cbb0fdc0cdcf.png)

---

**Option 3** with sub tabs (short headline):
![grafik](https://user-images.githubusercontent.com/57687516/109052017-75ba6f80-76db-11eb-8d69-c39ac06face4.png)

---

What is your voting?

**Comment by StephanStS** [comment]
My actual proposal is located there: https://github.com/StephanStS/DietPi-Docs/tree/dev-StS-hyperv

Unfortunately I have no english screenshots available.

**Comment by fpetru** [comment]
@StephanStS - While is the most verbose, I would still suggest to stay with Option 1.

- There are bigger differences to the end user, comparing to BIOS vs. UEFI installers. For virtualized editions, the differences are wider in terms of how the applications run, the selected options. They also run on different layers / editions (client vs. hypervisor). Just an example - see excellent article [DietPi with VMware hypervisor ESXi](https://ccie.tv/running-dietpi-vmware-image-on-esxi-6-7/), which is different than VMware Player. The same applies to Microsoft solution Hyper-V.
- Virtualized environments are second in rank - so they need space :)

**Comment by StephanStS** [comment]
@fpetru: Ok, convinced. I change to Option 1.  :smile:
