### ISSUE TITLE
Resolve InfluxDB presented two times

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#400]
We have it in web development: https://dietpi.com/docs/software/webserver_stack/#influxdb
And in hardware projects: https://dietpi.com/docs/software/hardware_projects/#influxdb

It's not a big issue in this particular case where it might fit well into both categories, but doing such for more software titles creates unnecessary overhead, also for enhancing/extending those docs, and creates confusion. So I'd like to remove this consequently.

Two ideas:
1. Leave InfluxDB in web development and move Grafana from hardware projects to system stats, where it actually fits well together with Netdata. The hardware projects category is large and a bit unspecific anyway.
2. Make a dedicated database category. This would fit as well since most databases can be used for various purposes, not just for web development. It would take them out of the web server stack context, so that not all components of LAMP are on the same page.

**Comment by fpetru** [comment]
Hi @MichaIng @StephanStS , Personally I would go for the second option. Indeed, databases & data stores are more versatile, and there are a good fit to various contexts, and not only web development.
