### ISSUE TITLE
filebrowser web file sharing

### ISSUE THREAD

**Issue by CouldBeThis** [MichaIng/DietPi-Docs#447]
I am not sure if there is any criteria for choosing software to include but perhaps [filebrowser](https://filebrowser.org/) might be of interest. 

It creates a very simple web file sharing interface with text editor and ability to selectively run shell commands should you configure it so. Perfect on mobile. Zero bloat.

**Comment by MichaIng** [comment]
This repository is about the documentation only. Software requests go to the main repository, although one for filebrowser exists already: https://github.com/MichaIng/DietPi/issues/2560
