### ISSUE TITLE
Pi-hole | Add tab about pihole-FTL.db TTL

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#476]
This database grows from hundreds for MiBs to GiBs, as the default long-term log time is at least 1 year. On slower SBCs like RPi Zero this leads to very long query times when e.g. searching for requests via web interface.

Most users won't need more than 1-2 weeks to check whether blocklists work or to search for requests that failed or unexpectedly were not blocked shortly before. So we might want to reduce the default log time. But that should be documented in the first place.

**Comment by StephanStS** [comment]
This could be achieved with the option MAXDBDAYS (e.g. `MAXDBDAYS=7` for storage of seven days).  
See https://docs.pi-hole.net/ftldns/configfile/#maxdbdays.

Additionally, use the DBINTERVAL option to reduce the write accesses to the file pihole-FTL.db (e.g. `DBINTERVAL=60` to write only every 60 minutes).  
See https://docs.pi-hole.net/ftldns/configfile/#dbinterval. 

I am also running with `BLOCKINGMODE=IP-NODATA-AAAA`.  
See https://docs.pi-hole.net/ftldns/blockingmode/#pi-holes-ip-ipv6-nodata-blocking the advantages compared to `BLOCKINGMODE=NONE`.

**Comment by MichaIng** [comment]
The default DBINTERVAL is one minute, right? 60 minutes is a bit extreme IMO, I mean all of this is stored in memory until written to disk and up to 1 hour of logs lost on power loss. 5 minutes would maybe make already some difference in terms of disk write overhead? But when it's about keeping a rotating disk silent, it doesn't make much difference, of course 😄.

We used `IP-NODATA-AAAA` in the past when the blocking page was enabled. But it is about to be removed from Pi-hole, as it cannot and did never work for HTTPS, which makes it mostly useless and not worth the overhead it produces for every blocked request. So we removed it from DietPi a while back and only use `NONE` since then, which is the recommended default by Pi-hole devs.

**Comment by StephanStS** [comment]
Yes, default DBINTERVAL is one minute. A log loss of typ. 30 minutes would not be a problem for me, I normally use the log to see what was blocked. In case of a system crash the log information seems not to be of interest for me. Otherwise, the default value would be o.k.  
I changed it to reduce the SD card write cycles for a longer lifetime.

**Comment by MichaIng** [comment]
> A log loss of typ. 30 minutes would not be a problem for me, I normally use the log to see what was blocked. In case of a system crash the log information seems not to be of interest for me.

For me personally it would be no problem either. I would likely run all in memory. So seems it would be another task to find out whether our users actually make use of the long-term logs, and how. If most use it like us, a default could even to be link it to RAM completely with a very short life time, for looking up issues or infos about requests that happened shortly before, like max 48h then. That would dramatically reduce CPU and disk impact of Pi-hole, I think. Or we give the choice for it during install/reinstall, a clear interactive dialogue to inform about such significant change is required anyway.

> I changed it to reduce the SD card write cycles for a longer lifetime.

Actually, theoretically it should not matter for absolute disk writes (=> lifetime) how often you write changes to the on-disk database. If you have a specific size of logs (=> database table entries) in one hour, it would not matter it you write them in 10 chunks or in 1. Especially with the filesystem cache as another buffer layer, even block size related overhead should be minimal. At least I remember talking about exactly that with a Pi-hole dev once (DL6ER, major FTL developer, so deals with SQLite queries all the time), that changes to an SQLite database do not cause much more writes than the size of the actually added/changed database entries themselves, i.e. quite efficient. But I never verified it with tests, actually. Would be interesting to compare some iotop accumulated write statistics, if there is any significant difference observable 🙂.

**Comment by StephanStS** [comment]
I propose not to ask users. Instead set a value for `DBINTERVAL` and describe in a tab why and how to change this.

**Comment by MichaIng** [comment]
Okay. Let's also pick up that question later today.

**Comment by Joulinar** [comment]
I personally use the log in case things are blocked right that moment to see what is it. I never used it for historical research. Losing the while db file would be fine for me es well 🤣

**Comment by StephanStS** [comment]
> I personally use the log in case things are blocked right that moment to see what is it. I never used it for historical research. Losing the while db file would be fine for me es well rofl

100% identical to me. :-)

**Comment by StephanStS** [comment]
@MichaIng: Result from discussion (am I right?):

- configuration in pihole-FTL.conf is set to 2 days during the installation (-> issue for DietPi necessary)
- we describe the change to a longer duration in a tab "logging database"
- we set the label "next version" to synchronize the code and docu changes

**Comment by StephanStS** [comment]
@MichaIng: Is there a DietPi issue for this which we could link to synchronize both issues (Code+Doc)? I did not find one.
Shall we focus this for 7.3? What is your opinion?

**Comment by Joulinar** [comment]
I guess not yet done. Let's move to 7.3

**Comment by MichaIng** [comment]
As the change is trivial an well discussed, I opened a PR to add it to v7.2 already: https://github.com/MichaIng/DietPi/pull/4430
