### ISSUE TITLE
Add documentation for new SBCs supported in 7.2

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Docs#490]

**Comment by fpetru** [comment]
@MichaIng - To extend the Docs, would these SBC have dedicated image downloads ?

- Pinebook Pro | Initial hardware identifier (ID: 46)  Support for this device has been added to DietPi.
- NanoPi R4S | Initial hardware identifier (ID: 47)  Support for this device has been added to DietPi.
- NanoPi R1 | Initial hardware identifier (ID: 48)  Support for this device has been added to DietPi.

**Comment by MichaIng** [comment]
They will have, but the images are not yet there. I'll create them today, but they'll be beta images for two reason: Run with DietPi v7.2 beta code and run with Debian Bullseye 😃! I take the chance to use those as first Bullseye testing images as well.

**Comment by fpetru** [comment]
@MichaIng - I'll the documentation (both in Docs & Website) soon after we launch release 7.2, and generate the images.

**Comment by MichaIng** [comment]
New images have been created and website update is in the pipeline. Let's update the docs accordingly.
