### ISSUE TITLE
Add DietPi v7.3 release notes

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#519]
@fpetru 
Do you find time to forge them? The list is quite short this month: https://github.com/MichaIng/DietPi/issues/4498

**Comment by fpetru** [comment]
Added an initial commit of the release notes (#522). I will commit later today also the extended version.

**Comment by MichaIng** [comment]
Many thanks.

**Comment by fpetru** [comment]
@MichaIng - slightly more expanded, and few issues fixed. In my view, it should not be a stopper for 7.3 release.
