### ISSUE TITLE
Tabbed sets are not working

### ISSUE THREAD

**Issue by DimitrijeDragasevic** [MichaIng/DietPi-Docs#536]
HI here is my env :
mkdocs                                     1.2.1
mkdocs-material                      7.1.11
mkdocs-material-extensions  1.0.1
pymdown-extensions               8.2

And here is the code that i am building:
`=== "MySQL"

```sql

delete from ci_summary_audits where created_dtm < ? limit ?

```

=== "SQL Server"

```sql

delete top (?) from ci_summary_audits where created_dtm < ?

````

and these get rendered as this picture :
<img width="722" alt="Screenshot 2021-07-21 at 14 01 16" src="https://user-images.githubusercontent.com/19540608/126485791-3cf3db42-b59a-46f8-8c3a-f984c65b57aa.png">
i think that they should render under one tabbed set not two

**Comment by MichaIng** [comment]
Many thanks for your report. This looks like a question towards pymdown, or are you working on a contribution for our documentation (which would be highly appreciated)?

The content of the tabs needs to be intended. Any unindented content is interpreted as the end of the tab:
```md
=== "MySQL"

    ```sql
    delete from ci_summary_audits where created_dtm < ? limit ?
    ```

=== "SQL Server"

    ```sql
    delete top (?) from ci_summary_audits where created_dtm < ?
    ```
```

**Comment by DimitrijeDragasevic** [comment]
thanks for the answer , but i made a mistake and posted it here, and btw your answer it correct xD

**Comment by MichaIng** [comment]
I thought so 😄. No problem and great that it works now.
