### ISSUE TITLE
Update Blynk server docs

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#545]
According to changes with DietPi v7.5: https://github.com/MichaIng/DietPi/pull/4594
Add some notes about how to do a test via `client-tcp-local.js` and the Android app. The original "blynk-client" JS library command does not work anymore, at least not with the auto-generated TLS certificate.

**Comment by fpetru** [comment]
Hi @MichaIng  - please share more updates or a web reference on how to do a test via `client-tcp-local.js` and the Android app. Thank you.
