### ISSUE TITLE
O!MPD | Add hint about youtube-dl related settings

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#552]
As of: https://github.com/MichaIng/DietPi/issues/4631

**Comment by StephanStS** [comment]
@MichaIng: What should be the text for the hint?

An own tab named "FAQ".
FAQ-headline **Why do my Youtube streams do not play?**
FAQ-text *This may occur e.g. in case you reinstalled 'youtube-dl' (software title 195) or if from improper configration relicts. In this case you need to edit the file 'config.local.inc.php' (located in /var/www/ompd/include) and delete/comment out the lines regarding 'python_path' and 'youtube-dl_path'. Then restart your system.*

**Comment by MichaIng** [comment]
Obsolete since v7.8. We now adjust the shebang instead of creating a shell wrapper to mitigate the issue, so that using an explicit O!MPD path for `youtube-dl` does not cause any issues anymore.
