### ISSUE TITLE
Add File Browser documentation

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#569]
https://github.com/MichaIng/DietPi/pull/4686

**Comment by StephanStS** [comment]
@MichaIng: To gather information for the docu (from #4686):

- executable location `/opt/filebrowser/`
- config file location `/mnt/dietpi_userdata/filebrowser/`
- user home `/mnt/dietpi_userdata/filebrowser/`
- add user `filebrowser` to group `dietpi`
- service executed as user `filebrowser`
- service executed as group `dietpi`
- should we lock `File Browser` to a specific directory like `/mnt/` or give full access
- default user to login `root`, `dietpi` or `filebrowser`
- port to be used 8085
- based on https://filebrowser.org/. The docu will reference quite a lot on this.

Q1: I cannot login via user `root` resp. `filebrowser`. Are there special credentials?

**Comment by Joulinar** [comment]
I will do the documentation. Just need some time.

**Comment by MichaIng** [comment]
Login credentials are `dietpi` and global software password.

We were thinking about whether to use something more specific like `filebrowser` or something very generic like `root` or `admin`. Arguments against the latter is that these are the commonly used by bots to try brute-forcing and a very specific login may be nasty to remember and e.g. to easily store in password managers/browsers when multiple web applications run on the same domain/IP. So `dietpi` seems to be a good compromise. But I'm open for suggestions on this, and then we may follow the same for all software titles to have a consistent experience.

**Comment by StephanStS** [comment]
With login `root` and `filebrowser` this occurs:
![grafik](https://user-images.githubusercontent.com/57687516/133593731-2fc3c674-d111-48c8-880a-bfeb0cc21211.png)

Login `dietpi` works fine.

**Comment by Joulinar** [comment]
we just setup a single user `dietpi`. Other users are not working.

**Comment by MichaIng** [comment]
Hey guys, do you already have something to commit? Else I'll write a simple entry now.

**Comment by MichaIng** [comment]
Done, see here: https://github.com/MichaIng/DietPi-Docs/pull/573/files#diff-c2750cc6061ca84efc31127a623955a4f002d395918dd19a2d5e02012b22a475

**Comment by Joulinar** [comment]
Unfortunately I don't have real network connection, just being only with my mobile phone. If you could do the initial entry would be perfect. I could enhance it next week if that would be ok for you.
