### ISSUE TITLE
HowTo | Enable Airsonic Jukebox mode

### ISSUE THREAD

**Issue by stownplayer** [MichaIng/DietPi-Docs#608]
#### Required Information
- DietPi version | `cat /DietPi/dietpi/.version`
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=25
G_DIETPI_VERSION_RC=3
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
stretchcat /etc/debian_version

- Kernel version | `uname -a`
`Linux SubsonicHome 4.19.42-v7+ MichaIng/DietPi#1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux`

- SBC device | `echo $G_HW_MODEL_DESCRIPTION` or (EG: RPi3)
RPi 3 Model B+ (armv7l)

- Power supply used | (EG: 5V 1A RAVpower)
pi store brand - 5v 1amp
- SDcard used | (EG: SanDisk ultra)
Sandisk extreme

#### Additional Information (if applicable)
- Software title |  Subsonic
- Was the software title installed freshly or updated/migrated? Installed in January
- Can this issue be replicated on a fresh installation of DietPi? Yes
   71e51554-7012-4383-b8d9-f9b91d180a1c

- Bug report ID | `sed -n 5p /DietPi/dietpi/.hw_model`

#### Steps to reproduce

1. ... Install and configure subsonic. No special setup. Audio and server work flawless once music shares are added and scanned. When playing music from an app like Play:sub and selecting jukebox mode, which should output sound on the pi3, there is no sound. 
2. ...

#### Expected behaviour
 There should be sound output on the 3mm jack when I play the app in jukebox mode.
- ...

#### Actual behaviour
 No sound
- ...

#### Extra details

sound works on the pi using aplay and testing a wave file. No issues. The jukebox mode is the only issue. I've also tested hifiberry dac and get the same results. System sound with aplay works but Subsonic won't output sound. 

The issue seems related to Java sound settings. See the link below. Seems the java settings in the subsonic settings does not use the correct audio device. I would test further but I'm unable to get an accurate list of java audio devices in the format "NVidia [plughw:0,3]" for example. This seems to be at the root of the issue and I don't know if that is an issue that can be solved by the underlying os or if it's simply a Subsonic issue. 
http://forum.subsonic.org/forum/viewtop ... java+sound
- ...

**Comment by MichaIng** [comment]
This has become trivial with Airsonic Advanced, can all be done by changing/adding a related player via web interface, no Java config hassle required anymore. Marking this as closed.
