### ISSUE TITLE
DietPi-Dashboard | Add docs tab about backend-only/multi-node setup

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#655]
https://github.com/MichaIng/DietPi/pull/5119

**Comment by ravenclaw900** [comment]
It should point out that, currently, only backend nodes can be used in a multi-node setup. Frontend nodes can't be connected with other frontend nodes.

**Comment by MichaIng** [comment]
Ah important hint. Intuitively I tested it like that, but make sense to add this info to the docs.
