### ISSUE TITLE
MinIO Documentation has incorrect username/password

### ISSUE THREAD

**Issue by holocronology** [MichaIng/DietPi-Docs#688]
MinIO [documentation here](https://dietpi.com/docs/software/cloud/#minio) provides the wrong default username and password.

Correct should be:

Username: minioadmin
Password: minioadmin

**Comment by MichaIng** [comment]
Many thanks. Obviously this changed.

**Comment by holocronology** [comment]
Sorry, realized I posted in wrong location originally and re-posted here before I saw you moved it.

**Comment by MichaIng** [comment]
Let's stay here now 😄.
