### ISSUE TITLE
DietPi-Software | OwnCloud

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi-Docs#702]
Hi guys,

I would recommend to remove the OwnCloud YouTube video as it's completely outdated (Debian Stretch + DietPi 6.17). As well it is giving complete incorrect instructions, like creating an own Database, removing config files and how to use external storage as data directory. 

https://www.youtube.com/watch?v=-OatWtH1Z9c&t=10s
https://www.avoiderrors.com/set-up-raspberry-pi-owncloud-server/

We have a user who end up with this on our forum https://dietpi.com/phpbb/viewtopic.php?t=10151

**Comment by MichaIng** [comment]
I remember another guide which similarly contained these wrong steps, but it was from a time where it was really required since our ownCloud install didn't to the `occ install` that time. But these are much newer. Bad that I missed to review them when they were added.
