### ISSUE TITLE
Add PHP Composer docs

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#708]
Logo see dietpi-software-php-composer.png in images directory (comes with branch dev-StS-releasenotes_8.3

**Comment by MichaIng** [comment]
Thanks for opening the issue, I'd have forgotten it 😄.

**Comment by StephanStS** [comment]
@MichaIng: Should this be an extra chapter there: https://dietpi.com/docs/software/webserver_stack/#php (i.e. an own chapter between PHP and Flask)?

**Comment by MichaIng** [comment]
Jep that sounds reasonable 👍.
