### ISSUE TITLE
YaCy ducumentation missing completely

### ISSUE THREAD

**Issue by SomeOrdinaryDude** [MichaIng/DietPi-Docs#727]
I even tried the Way Back Machine, but I found no results, suggesting there was never any documentation. I can't even figure out the default password and username to access the configuration.

**Comment by Joulinar** [comment]
try to clear your browser cache

**Comment by SomeOrdinaryDude** [comment]
> try to clear your browser cache

No luck, tried using a completely fresh install of a chromium based browser, nothing changed form firefox.

**Comment by SomeOrdinaryDude** [comment]
![image](https://user-images.githubusercontent.com/79510944/170578525-a497c014-6d7d-47fe-ab36-fa1d65dbce6d.png)

**Comment by Joulinar** [comment]
ok this is an issue on the web site and not the docs. On Docs this is fine

![image](https://user-images.githubusercontent.com/47155374/170578934-7f5c976b-002f-409f-b486-f2b33fdcdabb.png)

**Comment by MichaIng** [comment]
This list is incomplete, we fail to find time updating and complementing it: https://github.com/MichaIng/DietPi-Website/issues/20

Use this one: https://dietpi.com/docs/software/
Also `dietpi-software` should show you the new docs URLs correctly.

**Comment by SomeOrdinaryDude** [comment]
Yeah thanks for the help, I understand what the problem was now. My issue is solved.
