### ISSUE TITLE
(HomeAssistant 157 ) Default port number

### ISSUE THREAD

**Issue by MDAR** [MichaIng/DietPi-Docs#755]
Tiny typo in instructions

Re this page

https://dietpi.com/docs/software/home_automation/#:~:text=The%20web%20interface%20is%20accessible%20via%20port%208124%20resp.,:8124

I tried port 8124 for ages and kept restarting HomeAssistant

Just out of curiosity, I tried port ```8133```....

The rest is history

**Comment by Joulinar** [comment]
I transferred the issue to our docs repository. 

But you don't linked HA. This is `Domoticz` application. Did you looked for the correct docs?

**Comment by MDAR** [comment]
My apologies.


You are correct, I didn't scroll up and see the instructions for HA.
