### ISSUE TITLE
XRDP | Add troubleshooting section with RDP client settings

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#770]
As of: https://github.com/MichaIng/DietPi/issues/5704#issuecomment-1229365740

**Comment by StephanStS** [comment]
@MichaIng: Shall we shortly mention this article https://techdirectarchive.com/2022/01/15/how-to-resolve-microsoft-rdp-connection-black-screen/ in a tab there: https://dietpi.com/docs/software/remote_desktop/#xrdp?

**Comment by MichaIng** [comment]
It could be even just linked within an info block at the bottom of the main tab, what you think?
