### ISSUE TITLE
tailscale process name wrong in instructions

### ISSUE THREAD

**Issue by bt61** [MichaIng/DietPi-Docs#785]
I'm happy to see Tailscale added to softwares!

I couldn't get 'systemctl stop tailscale' to work, so I checked htop and see that the system process name is 'tailscaled' (add a 'd' on the end).   Using that with systemctl works perfectly.  The instructions (https://dietpi.com/docs/software/vpn/#tailscale) need that minor correction.  Setup, logs, and updates seem to use 'tailscale', just service control uses 'tailscaled'.

**Comment by MichaIng** [comment]
Totally right!

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi-Docs/commit/24d7e92
Thanks for the hint!
