### ISSUE TITLE
Possibility to open a specific page tab

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#79]
Currently when accessing https://dietpi.com/docs/user-guide_installation/, the SBC install steps are shown, which is perfectly fine.

However, it would be nice it there was a way to have the UEFI or VirtualBox instructions opened, e.g. via `#something` or query string.

There are even individual page links for the separate tabs "Introducion" header, `#introduction_1` and `#introduction_2`, but appending those to the URL does not switch the tab: https://dietpi.com/docs/user-guide_installation/#introduction_2

This is basically the downside of having the instructions merged into a single HTML page, but the much cleaner navigation and seamless switch between instructions was totally worth it, IMO 😃.
________________
Although the way to achieve is likely different, the same would be awesome for our download page: To have a single SBC description opened and scrolled to. This is the first thing I'll take care of, as I know the code and should be pretty easy by parsing page link or query string from URL in JavaScript. I'll then also add a possibility to have the SBC brand/type mixer showing a certain subset directly. Both are JavaScript functions which are initialised in a certain way with "All" and "Hidden" but can be simply initialised a different way.

**Comment by fpetru** [comment]
This would be an excellent improvement !

**Comment by MichaIng** [comment]
Here the issue about the implementation of this extension where the question to make anchors/links to tabs + open them has been discussed: https://github.com/facelessuser/pymdown-extensions/issues/814
So an ID exists but without custom JavaScript it is not possible to have the tab opened when linking it or a header inside a tab. I think for now we can live with it. If a topic is that important that it needs to be linked explicitly, it should have an own header instead of being "hidden" behind a tab. Else the header above the tabs group can be linked.
