### ISSUE TITLE
Docu changes for "Home Assistant: Install HACS by default"

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#790]
See PR [#5802 DietPi-Software | Home Assistant: Install HACS by default](https://github.com/MichaIng/DietPi/pull/5802).

Text from release notes v8.10:  
The Home Assistant Community Store (HACS) is now installed by default. For existing installs, do a reinstall: `dietpi-software reinstall 157`. To activate HACS, follow this guide: https://hacs.xyz/docs/configuration/basic/. 

Where to change: Home Assistant - https://dietpi.com/docs/software/home_automation/#home-assistant

The sentence "To activate HACS, follow this guide: https://hacs.xyz/docs/configuration/basic/" is part of the documentation.  
It has to be decided/defined whether a short info about the default installed HACS should be added.

**Comment by MichaIng** [comment]
You mean to add another tab or so? Since users need to go through this little ugly but mandatory service restart loop, it's hard to overlook this sentence as optional final setup step. The info is also printed by `dietpi-software` to console.

What about wrapping the sentence into an `!!! info` block, to make it more visible?

**Comment by MichaIng** [comment]
The same short info is printed during install and part of the "Initial install and access" in docs already, but both are not highlighted very much. We could make the info during install a prompt, and/or we could wrap the sentence in docs into an info block to highlight it better. And we could align the sentences, e.g.:
```sh
The Home Assistant Community Store (HACS) is installed as well. To activate it, follow this guide: https://hacs.xyz/docs/configuration/basic/
```
