### ISSUE TITLE
Update myMPD docs

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#802]
https://github.com/MichaIng/DietPi/pull/5944
- SSL is now enabled by default, hence remove related `Installation notes` tab and update web UI access URL.
- The configuration can be changed in `/var/lib/mympd/config` since a while. Make `Configuration` tab.
- A new web UI screenshot would be great, since it has changed quite significantly.
- Add linkes to [official docs](https://jcorporation.github.io/myMPD/), [GitHub](https://github.com/jcorporation/myMPD), [GPLv3 license](https://github.com/jcorporation/myMPD/blob/master/LICENSE.md).

**Comment by Joulinar** [comment]
@MichaIng @StephanStS I started working to update myMPD docs. Feel free to add your comments or updated. We still would need a new picture.
