### ISSUE TITLE
Samba package: Add a tab about wsdd

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#823]
Q: Shall we add a tab page about wsdd at the [samba docu](https://dietpi.com/docs/software/file_servers/#samba)?

See https://dietpi.com/forum/t/samba-share/6285/6. Contents could be:
- Tab name "Web Service Discovery daemon"
- Contents
  - In case of problems with the Samba share not showing up in the Windows network view, the wsdd daemon can be installed
  - ... description of installation and configuration

@MichaIng, @Joulinar: Your opinion?

**Comment by Joulinar** [comment]
https://github.com/MichaIng/DietPi/discussions/5244

Maybe we should continue this one.

**Comment by MichaIng** [comment]
Ah yeah, reasonable. The docs tab could be added first as well, and we then move install instructions to `dietpi-software` code when implementing it, or the other way round.
