### ISSUE TITLE
Domoticz | add user + password information

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi-Docs#868]
From 2023.1 Stable: By default Domoticz is protected by a username (admin) and password (domoticz).

https://www.domoticz.com/wiki/Getting_started

**Comment by MichaIng** [comment]
Probably we can adjust this to be `dietpi` and global software password.

**Comment by Joulinar** [comment]
I had a very brief look yesterday. Some more research would be needed, indeed.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi-Docs/commit/ee9c48e

**Comment by Joulinar** [comment]
thx @MichaIng
