### ISSUE TITLE
Add Moonlight docs

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#873]
https://github.com/MichaIng/DietPi/pull/6303

Should contain:
- Links to supported streaming host software, most importantly the FLOSS Sunshine: https://github.com/LizardByte/Sunshine
- Link to Sunshine docs? E.g. here how I got it working without issues on Windows with the portable version: https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/usage.html#windows
- Quick start instructions:
```sh
moonlight pair HOST # hostname or IP, can be omitted for auto-detection but this did not work in my case
# enter shown PIN on HOST web UI
moonlight stream -app Desktop HOST # Stream desktop as example
```

**Comment by mtekman** [comment]
On a windows machine,  running `cmd` → `cd C:\Program Files\Sunshine\; sunshine.exe -0` saves me from having to use the webui (in case of forgotten password), and allows you to enter a PIN directly into stdin

**Comment by MichaIng** [comment]
I started it via service according to docs:
```bat
cd /d "C:\Path\To\Sunshine\scripts"
install-service.bat
```
I tried it just double-clicking the `sunshine.exe` first, which did not work: The web UI was reachable but Moonlight could not detect. The `-0` arg is required then?

Found [/etc/moonlight.conf](https://github.com/moonlight-stream/moonlight-embedded/blob/master/moonlight.conf) which allows to add the HOST, default app etc. There one can also define the A/V decoder. I see `omx` there (OpenMAX) as RPi decoder. This is probably the issue why it fails at least with 64-bit kernel, as this does not support OpenMAX (heading over to PR).

**Comment by MichaIng** [comment]
The config file `/etc/moonlight.conf` can be used to set default host, app, resolution etc, but it needs to be explicitly loaded:
```sh
moonlight /etc/moonlight.conf
```
Looks like it was made for running as service. I'll implement a service, service user and autostart option next week.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi-Docs/commit/bb561cf
@mtekman I btw found the magic button to exit streaming:
CTRL+ALT+SHIFT+Q: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-options
