### ISSUE TITLE
Correct/optimize link checker action

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#88]
The link checker via peter-evans/link-checker throws a couple of errors which could be overcome by optimizing the file .github/workflows/actions.yml: 

- Exclude from link check via command line "-r \<regex\>"
  - http://localhost
  - http://192.168.0.100
- Exclude file build/docs/release-notes.md and dietpi_docs_todo.md from getting link checked
  - possibly via any command line option (don't know how)
  - moving these two files from the directory build/docs (this would also help for the Markdown check)

See also section "Check links in html files", error output of one of the pull request [action logs](https://github.com/MichaIng/DietPi-Docs/runs/1268831284?check_suite_focus=true).

**Comment by StephanStS** [comment]
Solved by excluding localhost, 192.168.0.100, github.com via the actions.yml file.

**Comment by MichaIng** [comment]
An alternative would be to not expose that strings as clickable links at all, but wrapping them into code tags. Or, replace those with `<your.domain/IP>` or something like that.
