### ISSUE TITLE
Small change needed in documentation for Jellyfin after migrating to Bookworm 

### ISSUE THREAD

**Issue by echtfrank** [MichaIng/DietPi-Docs#896]
After migrating from Bullseye to Bookworm, Jellyfin doesn't use "jellyfin-ffmpeg" anymore, but uses "jellyfin-ffmpeg5" instead.
In the [documentation](https://dietpi.com/docs/software/media/#jellyfin) under tab "Update to latest version" the code block must be changed as well:

From (Bullseye and earlier):
```
apt update
apt install jellyfin jellyfin-ffmpeg

```
To (Bookworm):
```
apt update
apt install jellyfin jellyfin-ffmpeg5
```

**Comment by MichaIng** [comment]
Thanks for the hint. It is not only on Bookworm but the same package is available on their Bullseye and Buster suites as well. FFmpeg 5 vs FFmpeg 4 this is.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi-Docs/commit/13deb3a

**Comment by echtfrank** [comment]
Thanks for your better investigation ;-)

**Comment by echtfrank** [comment]
I was thinking: is there any functional difference between executing the aforementioned CLI-commands versus `dietpi-sofware reinstall 178`?
