### ISSUE TITLE
Move MediaWiki from 'cloud' to 'social' and change heading level

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#907]
Mediawiki should be described in ['social'](http://localhost:8000/docs/software/social/) instead of ['cloud'](https://dietpi.com/docs/software/cloud/)

Heading level has to be corrected.

**Comment by MichaIng** [comment]
I agree with you that it fits better into "social", but it currently matches `dietpi-software`. So we would need to move it there first, and then do the docs change after next release.

**Comment by StephanStS** [comment]
> I agree with you that it fits better into "social", but it currently matches `dietpi-software`. So we would need to move it there first, and then do the docs change after next release.

Ok. Shall I open a DietPi issue?

**Comment by MichaIng** [comment]
I was just having it open anyway: https://github.com/MichaIng/DietPi/commit/2abad37
